#!/usr/bin/env bash
echo -e '\n' '/bookstore/book/title' '\n'
xpath -q -e \
  '/bookstore/book/title' \
  books1.xml
echo -e '\n' '/bookstore/book[1]/title' '\n'
xpath -q -e \
  '/bookstore/book[1]/title' \
  books1.xml
echo -e '\n' '/bookstore/book/price[text()]' '\n'
xpath -q -e \
  '/bookstore/book/price[text()]' \
  books1.xml
exit $?
