#!/usr/bin/env bash
xpath -q -e \
  'bookstore' \
  books.xml
xpath -q -e \
  '/bookstore' \
  books.xml
xpath -q -e \
  '/bookstore/book' \
  books.xml
xpath -q -e \
  '//book' \
  books.xml
xpath -q -e \
  'bookstore//book' \
  books.xml
xpath -q -e \
  '//@lang' \
  books.xml
xpath -q -e \
  '/bookstore/book[1]' \
  books.xml
xpath -q -e \
  '/bookstore/book[last()]' \
  books.xml
xpath -q -e \
  '/bookstore/book[last()-1]' \
  books.xml
xpath -q -e \
  '/bookstore/book[position()<3]' \
  books.xml
xpath -q -e \
  '//title[@lang]' \
  books.xml
xpath -q -e \
  '//title[@lang="eng"]' \
  books.xml
xpath -q -e \
  '/bookstore/book[price>35.00]' \
  books.xml
xpath -q -e \
  '/bookstore/book[price>35.00]/title' \
  books.xml
xpath -q -e \
  '/bookstore/book[attribute::cat!="fiction" and price>50.00]/title' \
  books.xml
xpath -q -e \
  '/bookstore/book[attribute::cat="textbook"]/price/text()' \
  books.xml
exit $?
