#!/usr/bin/env bash
echo
echo Query:
cat books.query
echo 
echo Result:
saxon -q:books.query
echo $'\n\n'
echo Query:
cat booksnext.query
echo
echo Result:
saxon -q:booksnext.query
echo $'\n\n'
echo Query:
cat titleprice.query
echo
echo Result:
saxon -q:titleprice.query
echo
echo $'\n\n'
echo Query:
cat nonfiction.query
echo
echo Result:
saxon -q:nonfiction.query
echo $'\n\n'
echo Query:
cat maxprice.query
echo
echo Result:
saxon -q:maxprice.query
echo
exit $?
