#!/usr/bin/env bash
xmllint --xpath \
  '/bookstore/book[attribute::cat!="fiction" and price>50.00]/title' \
  books.xml
xmllint --xpath \
  '/bookstore/book[attribute::cat="textbook"]/price/text()' \
  books.xml
exit $?
