#!/usr/bin/env bash
echo -e '\n' '/catalog/product' '\n'
xpath -q -e \
  '/catalog/product' \
  catalog.xml 
echo -e '\n' '/*/product/@dept' '\n'
xpath -q -e \
  '/*/product/@dept' \
  catalog.xml
echo -e '\n' '//product/@dept' '\n'
xpath -q -e \
  '//product/@dept' \
  catalog.xml
echo -e '\n' '/catalog/product[@dept = "ACC"]' '\n'
xpath -q -e \
  '/catalog/product[@dept = "ACC"]' \
  catalog.xml
echo -e '\n' '/catalog/product[2]' '\n'
xpath -q -e \
  '/catalog/product[2]' \
  catalog.xml
exit $?
