#!/usr/bin/env bash
echo
echo Query:
cat catprods.xquery
echo 
echo Result:
saxon -q:catprods.xquery
echo $'\n\n'
echo Query:
cat catdepts.xquery
echo 
echo Result:
saxon -wrap -q:catdepts.xquery
echo $'\n\n'
echo Query:
cat catdepts2.xquery
echo 
echo Result:
saxon -wrap -q:catdepts2.xquery
echo $'\n\n'
echo Query:
cat catprods2.xquery
echo 
echo Result:
saxon -q:catprods2.xquery
echo $'\n\n'
exit $?
