#!/usr/bin/env bash
echo
echo Query:
cat catprods.xquery
echo 
echo Result:
saxon -q:catprods.xquery
echo $'\n\n'
echo Query:
cat catdepts.xquery
echo 
echo Result:
saxon -wrap -q:catdepts.xquery
echo $'\n\n'
echo Query:
cat catdepts2.xquery
echo 
echo Result:
saxon -wrap -q:catdepts2.xquery
echo $'\n\n'
echo Query:
cat catprods2.xquery
echo 
echo Result:
saxon -q:catprods2.xquery
echo $'\n\n'
echo Query:
cat catprods3.xquery
echo 
echo Result:
saxon -q:catprods3.xquery
echo $'\n\n'
echo Query:
cat catprods4.xquery
echo 
echo Result:
saxon -q:catprods4.xquery
echo $'\n\n'
echo Query:
cat catprods5.xquery
echo 
echo Result:
saxon -q:catprods5.xquery
echo $'\n\n'
echo Query:
cat catprods6.xquery
echo 
echo Result:
saxon -q:catprods6.xquery
echo $'\n\n'
echo Query:
cat catitems.xquery
echo 
echo Result:
saxon -q:catitems.xquery
echo $'\n\n'
echo Query:
cat aggbydept.xquery
echo 
echo Result:
saxon -q:aggbydept.xquery
echo $'\n\n'
echo Query:
cat catprods7.xquery
echo 
echo Result:
saxon -q:catprods7.xquery
echo $'\n\n'
echo Query:
cat catstring.xquery
echo 
echo Result:
saxon -q:catstring.xquery
echo $'\n\n'
echo Query:
cat catstring1.xquery
echo 
echo Result:
saxon -q:catstring1.xquery
echo $'\n\n'
echo Query:
cat catdata.xquery
echo 
echo Result:
saxon -q:catdata.xquery
echo $'\n\n'
echo Query:
cat catatomic.xquery
echo 
echo Result:
saxon -q:catatomic.xquery
echo $'\n\n'
echo Query:
cat catsequence.xquery
echo 
echo Result:
saxon -q:catsequence.xquery
echo $'\n\n'
echo Query:
cat catnocast.xquery
echo 
echo Result:
saxon -q:catnocast.xquery
echo $'\n\n'
echo Query:
cat catcast.xquery
echo 
echo Result:
saxon -q:catcast.xquery
echo $'\n\n'
echo Query:
cat catnumber.xquery
echo 
echo Result:
saxon -q:catnumber.xquery
echo $'\n\n'
exit $?
