#!/usr/bin/env bash
echo -e '\n' '//*[@*]' '\n'
saxon -qs:'//*[@*]' \
  -s:Hello.java.xml
echo -e '\n' '/MethodDeclaration//*[not(@*)]' '\n'
saxon -qs:'/MethodDeclaration//*[not(@*)]' \
  -s:Hello.java.xml
echo $'\n //MethodDeclaration[contains(@Name, "main")] \n'
saxon -qs:'//MethodDeclaration[contains(@Name, "main")]' \
  -s:Hello.java.xml
exit 0
