#!/usr/bin/env bash
echo
echo Query:
cat books.xquery
echo 
echo Result:
saxon -q:books.xquery
echo $'\n\n'
echo Query:
cat booksnext.xquery
echo
echo Result:
saxon -q:booksnext.xquery
echo $'\n\n'
echo Query:
cat titleprice.xquery
echo
echo Result:
saxon -q:titleprice.xquery
echo
echo $'\n\n'
echo Query:
cat nonfiction.xquery
echo
echo Result:
saxon -q:nonfiction.xquery
echo $'\n\n'
echo Query:
cat maxprice.xquery
echo
echo Result:
saxon -q:maxprice.xquery
echo
echo $'\n\n'
echo Query:
cat catsummary.xquery
echo
echo Result:
saxon -q:catsummary.xquery
echo
echo $'\n\n'
echo Query:
cat catprice.xquery
echo
echo Result:
saxon -q:catprice.xquery
echo
exit $?
