#!/usr/bin/env bash

usage() {
        echo "usage: '$0' {xqueryFile}"
        echo "xqueryFile - optional but must exist when specified"
        return 1
}

execsax() {

output="Query:\n\n"
output+=$(cat "$1")
output+="\n\n" 
output+='Result:\n\n'
output+=$(saxon -q:"$1")
output+="\n\n"
printf "$output"
return $?
}

xqueryFile="$1"
export -f execsax

if [ ! -z "$xqueryFile" ] && [ ! -f "$xqueryFile" ]
  then
    usage
    exit $?
fi

if [ ! -z "$xqueryFile" ] && [ -f "$xqueryFile" ]
  then
    execsax "$xqueryFile"
    exit $?
fi

find . -maxdepth 1 -type f -name "*.xquery" | \
  parallel -j 5 -I% --max-args 1 execsax %
exit $?
