#!/usr/bin/env bash

usage() {
        echo "usage: '$0' {xqueryFile}"
        echo "xqueryFile -  must exist"
        return 1
}


xqueryFile="$1"

if [ ! -z "$xqueryFile" ] && [ ! -f "$xqueryFile" ]
  then
    usage
    exit $?
fi

if [ ! -z "$xqueryFile" ] && [ -f "$xqueryFile" ]
  then
    ./execsaxon "$xqueryFile"
    exit $?
fi

find . -maxdepth 1 -type f -name "*.xquery" | \
  parallel -j 5 -I% --max-args 1 ./execsaxon %
exit $?
